// src/lib/LanguageContext.jsx
// Lightweight i18n — no external deps
// Supports: English, Français, Español, العربية
// Usage: const { t, lang, setLang, dir } = useLanguage()

import { createContext, useContext, useState, useEffect } from "react"

const en = {
  // Navigation
  nav_dashboard:"Dashboard", nav_journal:"Journal", nav_notebook:"Notebook",
  nav_calendar:"Calendar", nav_analytics:"Analytics", nav_reports:"Reports",
  nav_playbook:"Playbook", nav_sylledge:"SYLLEDGE AI", nav_backtesting:"Backtesting",
  nav_brokersync:"Broker Sync", nav_settings:"Settings", nav_calculator:"Calculator",
  nav_market_charts:"Market Charts", nav_admin:"Admin Panel",
  nav_upgrade:"Upgrade to Pro", nav_live:"Live",
  // Common actions
  save:"Save", cancel:"Cancel", delete:"Delete", edit:"Edit", add:"Add",
  clear:"Clear", close:"Close", confirm:"Confirm", search:"Search", filter:"Filter",
  export:"Export", import:"Import", loading:"Loading…", no_data:"No data yet",
  view_all:"View All", show_more:"Show more", done:"Done", retry:"Retry again",
  back:"Back", next:"Next", yes:"Yes", no:"No", new:"New", refresh:"Refresh",
  copy:"Copy", copied:"Copied!", connect:"Connect",
  // Common labels
  symbol:"Symbol", direction:"Direction", entry:"Entry", exit:"Exit",
  pnl:"P&L", pips:"Pips", outcome:"Outcome", session:"Session",
  timeframe:"Timeframe", quality:"Quality", date:"Date", time:"Time",
  notes:"Notes", tags:"Tags", actions:"Actions", win:"WIN", loss:"LOSS",
  breakeven:"BREAKEVEN", buy:"BUY", sell:"SELL", volume:"Volume",
  commission:"Commission", swap:"Swap", total:"Total", status:"Status",
  description:"Description", name:"Name", category:"Category",
  // Dashboard
  dash_title:"Dashboard", dash_new_trade:"New Trade", dash_net_pnl:"Net P&L",
  dash_win_rate:"Win Rate", dash_profit_factor:"Profit Factor",
  dash_expectancy:"Expectancy", dash_sylla_score:"SYLLA Score",
  dash_equity_curve:"Equity Curve", dash_recent_trades:"Recent Trades",
  dash_activity:"Activity Feed", dash_today:"Today",
  dash_heatmap:"Trading Activity", dash_daily_pnl:"Daily P&L",
  dash_log_trade:"Log New Trade", dash_no_activity:"No recent activity. Log your first trade!",
  dash_no_trades:"No trades yet. Hit the",
  dash_log_to_see:"Log trades to see chart", dash_log_2_trades:"Log 2+ trades to see score",
  dash_live:"Live", dash_account:"ACCOUNT", dash_quality:"Quality (1-10)",
  dash_date_time:"Date & Time", dash_setup_notes:"Setup, reasoning, lessons learned…",
  dash_no_daily:"No daily data yet",
  // Journal
  journal_title:"Trade Journal", journal_logged:"trades logged", journal_shown:"shown",
  journal_new_trade:"New Trade", journal_table:"Table", journal_calendar:"Calendar",
  journal_filters:"Filters", journal_clear_all:"Clear all", journal_replay:"Replay",
  journal_ai_review:"AI Review", journal_min_quality:"Min Quality",
  journal_pnl_range:"P&L Range ($)", journal_date_range:"Date Range",
  journal_filter_tag:"Filter by Tag", journal_running_pnl:"Running P&L",
  journal_no_trades:"No trades yet. Hit the + button!",
  journal_pre_entry:"Context (pre-entry)", journal_in_trade:"In trade",
  journal_closed:"Closed", journal_bars:"bars",
  // Notebook
  notebook_title:"Daily Notebook", notebook_premarket:"Pre-Market Plan",
  notebook_postmarket:"Post-Market Review", notebook_mindset:"Mindset & Discipline",
  notebook_bias:"Market Bias", notebook_watchlist:"Symbols to Watch",
  notebook_watchlist_ph:"XAUUSD, UK100, EURUSD…",
  notebook_plan:"Trading Plan & Key Levels", notebook_goals:"Goals for Today",
  notebook_review:"How did the day go?", notebook_lessons:"Lessons Learned",
  notebook_mistakes:"Mistakes to Fix", notebook_discipline:"Rule Discipline",
  notebook_day_summary:"Day Summary", notebook_no_trades:"No trades this day",
  notebook_day_pnl:"Day P&L", notebook_today:"Today",
  notebook_saving:"Saving…", notebook_saved:"Saved",
  notebook_mindset_state:"Today's Mindset", notebook_poor:"Poor",
  below_avg:"Below Avg", average:"Average", good:"Good",
  notebook_excellent:"Excellent", notebook_score:"Score",
  // Analytics
  analytics_title:"Analytics", analytics_period:"PERIOD:",
  analytics_account:"ACCOUNT:", analytics_symbol:"SYMBOL:",
  analytics_net_pnl:"Net P&L", analytics_win_rate:"Win Rate",
  analytics_profit_factor:"Profit Factor", analytics_expectancy:"Expectancy",
  analytics_max_dd:"Max Drawdown", analytics_avg_rr:"Avg R:R",
  analytics_total_fees:"Total Fees", analytics_periods:"Periods",
  analytics_profitable:"Profitable", analytics_unprofitable:"Unprofitable",
  analytics_best:"Best", analytics_worst:"Worst",
  analytics_equity_curve:"Equity Curve", analytics_outcome_dist:"Outcome Distribution",
  analytics_daily_pnl:"Daily P&L", analytics_by_session:"By Session",
  analytics_by_pair:"By Pair", analytics_by_tf:"By Timeframe",
  analytics_perf_pair:"Performance by Pair", analytics_wr_dow:"Win Rate by Day of Week",
  analytics_buy_sell:"BUY vs SELL", analytics_quality_pnl:"Quality vs P&L",
  analytics_streaks:"Streaks", analytics_drawdown:"Drawdown (%)",
  analytics_pnl_dist:"P&L Distribution", analytics_monthly:"Monthly Breakdown",
  // Reports
  reports_title:"Advanced Reports", reports_dimensions:"50+ dimensions",
  period_all:"All Time", period_ytd:"YTD", period_1y:"1 Year",
  period_6m:"6 Months", period_3m:"3 Months", period_1m:"1 Month", period_1w:"1 Week",
  // Backtesting
  bt_title:"Backtesting", bt_new_session:"New Session", bt_create_first:"Create First Session",
  bt_session_name:"Session Name", bt_session_ph:"e.g. XAUUSD London Breakout Q1",
  bt_initial_capital:"Initial Capital", bt_playbook:"Playbook", bt_no_playbook:"No playbook",
  bt_strategy:"Strategy Summary", bt_strategy_ph:"Describe the strategy being tested…",
  bt_notes_ph:"Additional notes…", bt_add_trade:"Add Trade", bt_save_trade:"Save Trade",
  bt_trades:"Trades", bt_equity_curve:"Equity Curve", bt_trade_pnl:"Trade P&L",
  bt_delete_title:"Delete Session?",
  bt_delete_desc:"This will permanently delete this backtesting session and all its trades.",
  // BrokerSync
  bs_title:"BrokerSync", bs_connected_accounts:"Connected accounts",
  bs_no_accounts:"No accounts connected yet", bs_connect_first:"Connect your first account",
  bs_connect_another:"Connect another account", bs_manage:"Manage",
  bs_how_to:"How to connect MT5", bs_choose_method:"Choose a connection method",
  bs_ea_connection:"EA Connection", bs_ea_subtitle:"Expert Advisor · Real-time",
  bs_ea_active:"Active", bs_direct:"Direct Credentials",
  bs_direct_subtitle:"MT5 login · No EA needed",
  bs_connecting:"Connecting to MT5…", bs_connected:"Connected!",
  bs_failed:"Connection Failed", bs_try_again:"Try again",
  bs_broker_name:"Broker name", bs_broker_ph:"e.g. Exness",
  bs_login:"MT5 Account Login", bs_login_ph:"409913367",
  bs_server:"Broker Server", bs_server_ph:"Exness-MT5Real10",
  bs_password:"Investor Password", bs_password_ph:"••••••••",
  bs_token:"Token", bs_token_ph:"Your EA token", bs_step:"Step",
  bs_ea_sync:"TradeSylla_Sync EA", bs_ea_market:"TradeSylla_MarketData EA",
  bs_direct_mt5:"Direct MT5 Connection",
  // Calculator
  calc_title:"Position Size Calculator", calc_rr_title:"Risk / Reward Calculator",
  calc_pip_title:"Pip Value Calculator", calc_pip_desc:"How much is each pip worth in USD",
  calc_risk_title:"Daily Risk Manager", calc_risk_desc:"Keep your daily drawdown under control",
  calc_balance:"Account Balance", calc_risk_pct:"Risk per Trade",
  calc_entry:"Entry Price", calc_entry_ph:"e.g. 2340.50",
  calc_sl:"Stop Loss", calc_sl_ph:"e.g. 2330.00",
  calc_tp:"Take Profit", calc_tp_ph:"e.g. 2375.00",
  calc_win_rate:"Your Win Rate", calc_risk_amount:"Risk Amount",
  calc_lot_size:"Lot Size", calc_stop_dist:"Stop Distance",
  calc_pip_value:"Pip Value", calc_units:"Units",
  calc_fill_all:"Fill in all fields to calculate",
  calc_fill_entry:"Fill in entry, SL, and TP to calculate",
  calc_fill_fields:"Fill in fields to calculate",
  calc_rr_ratio:"R:R Ratio", calc_reward:"Reward", calc_breakeven_wr:"Breakeven Win Rate",
  calc_risk_dist:"Risk Distance", calc_reward_dist:"Reward Distance",
  calc_risk_label:"Risk: $", calc_reward_label:"Reward: $",
  calc_value_per_pip:"Value per Pip", calc_pip_size:"Pip Size",
  calc_instrument:"Instrument", calc_pips_count:"Number of Pips",
  calc_market_price:"Current/Market Price (optional)", calc_market_desc:"For accurate pip value",
  calc_cross_price:"Current Price (for cross pairs)", calc_cross_desc:"Optional — improves accuracy",
  calc_max_daily:"Max Daily Loss", calc_planned_risk:"Planned Risk Today",
  calc_max_trades:"Max Trades Allowed", calc_risk_used:"Risk used",
  calc_max_daily_risk:"Max Daily Risk", calc_trades_today:"Trades Planned Today",
  // Playbook
  pb_title:"Playbook", pb_new:"New Strategy", pb_create_first:"Create first strategy",
  pb_delete_title:"Delete Strategy?",
  pb_delete_desc:"This will permanently delete this playbook strategy and all its data.",
  pb_strategy_name:"Strategy Name", pb_strategy_ph:"e.g. London Breakout",
  pb_category:"Category", pb_status:"Status", pb_description:"Description",
  pb_desc_ph:"Brief overview of this strategy…",
  pb_sessions:"Sessions", pb_timeframes:"Timeframes", pb_pairs:"Pairs",
  pb_custom_pairs:"Custom pairs/assets (comma separated)",
  pb_custom_ph:"e.g. BTCUSD, ETHUSD, TSLA",
  pb_entry_rules:"Entry Rules", pb_exit_rules:"Exit Rules", pb_risk_rules:"Risk Rules",
  pb_confluences:"DIRECTION-SPECIFIC CONFLUENCES & SETUPS",
  pb_long_conf:"LONG / BUY Confluences", pb_short_conf:"SHORT / SELL Confluences",
  pb_screenshots:"Setup Screenshots", pb_add_screenshot:"Add screenshot",
  pb_perf_targets:"Performance Targets (optional)",
  pb_target_wr:"Target Win Rate %", pb_target_pf:"Target Profit Factor",
  pb_target_rr:"Target Avg R:R", pb_add_notes:"Additional Notes",
  pb_target_wr_short:"Target WR", pb_target_pf_short:"Target PF",
  pb_target_rr_short:"Target R:R",
  // Settings
  settings_title:"Settings", settings_account:"Account",
  settings_appearance:"Appearance", settings_language:"Language",
  settings_data:"Data & Import", settings_api:"API Keys",
  settings_notif:"Notifications", settings_lang_title:"Display Language",
  settings_lang_desc:"Choose the language used across the entire app.",
  settings_lang_saved:"Language saved",
  settings_profile:"Profile Information", settings_display_name:"Display Name",
  settings_name_ph:"Your name", settings_currency:"Currency",
  settings_email:"Email", settings_bio:"Trading Style / Bio",
  settings_free_plan:"Free Plan", settings_upgrade:"Upgrade to Pro",
  settings_upgrade_btn:"Upgrade →", settings_theme:"Theme",
  settings_custom_colors:"Custom Colors", settings_data_summary:"Data Summary",
  settings_export:"Export Backup", settings_danger:"Danger Zone",
  settings_danger_clear:"Clear", settings_sure:"Are you sure?",
  settings_notif_prefs:"Notification Preferences",
  settings_rtl:"RTL", settings_saved:"Saved",
  settings_sylledge_key:"SYLLEDGE AI (Anthropic API Key)",
  settings_key_ph:"sk-ant-api03-…", settings_key_active:"SYLLEDGE AI is active and ready",
  settings_user_token:"TradeSylla_Sync EA Token",
  settings_admin_token:"SYLLEDGE Market Data EA Token",
  // SYLLEDGE
  sylledge_title:"SYLLEDGE AI", sylledge_placeholder:"Ask SYLLEDGE anything about your trading…",
  sylledge_thinking:"SYLLEDGE is thinking…", sylledge_no_playbook:"No active playbook",
  sylledge_no_insights:"No saved insights yet", sylledge_market:"Market Charts",
  // Errors
  err_load:"Failed to load data", err_save:"Failed to save",
  err_not_found:"Not found", err_auth:"Please log in again",
}

const fr = {
  nav_dashboard:"Tableau de bord", nav_journal:"Journal", nav_notebook:"Cahier",
  nav_calendar:"Calendrier", nav_analytics:"Analytiques", nav_reports:"Rapports",
  nav_playbook:"Stratégies", nav_sylledge:"SYLLEDGE IA", nav_backtesting:"Backtesting",
  nav_brokersync:"Courtier Sync", nav_settings:"Paramètres", nav_calculator:"Calculatrice",
  nav_market_charts:"Graphiques", nav_admin:"Admin",
  nav_upgrade:"Passer à Pro", nav_live:"En direct",
  save:"Enregistrer", cancel:"Annuler", delete:"Supprimer", edit:"Modifier", add:"Ajouter",
  clear:"Effacer", close:"Fermer", confirm:"Confirmer", search:"Rechercher", filter:"Filtrer",
  export:"Exporter", import:"Importer", loading:"Chargement…", no_data:"Aucune donnée",
  view_all:"Tout voir", show_more:"Afficher plus", done:"Terminé", retry:"Réessayer",
  back:"Retour", next:"Suivant", yes:"Oui", no:"Non", new:"Nouveau", refresh:"Actualiser",
  copy:"Copier", copied:"Copié !", connect:"Connecter",
  symbol:"Symbole", direction:"Direction", entry:"Entrée", exit:"Sortie",
  pnl:"P&L", pips:"Pips", outcome:"Résultat", session:"Session",
  timeframe:"Unité de temps", quality:"Qualité", date:"Date", time:"Heure",
  notes:"Notes", tags:"Étiquettes", actions:"Actions", win:"GAIN", loss:"PERTE",
  breakeven:"NEUTRE", buy:"ACHAT", sell:"VENTE", volume:"Volume",
  commission:"Commission", swap:"Swap", total:"Total", status:"Statut",
  description:"Description", name:"Nom", category:"Catégorie",
  dash_title:"Tableau de bord", dash_new_trade:"Nouveau trade", dash_net_pnl:"P&L net",
  dash_win_rate:"Taux de gain", dash_profit_factor:"Facteur de profit",
  dash_expectancy:"Espérance", dash_sylla_score:"Score SYLLA",
  dash_equity_curve:"Courbe d'équité", dash_recent_trades:"Trades récents",
  dash_activity:"Activité récente", dash_today:"Aujourd'hui",
  dash_heatmap:"Activité de trading", dash_daily_pnl:"P&L quotidien",
  dash_log_trade:"Enregistrer un trade", dash_no_activity:"Aucune activité. Enregistrez votre premier trade !",
  dash_no_trades:"Aucun trade. Cliquez sur",
  dash_log_to_see:"Enregistrez des trades pour voir le graphique",
  dash_log_2_trades:"Enregistrez 2+ trades pour voir le score",
  dash_live:"En direct", dash_account:"COMPTE", dash_quality:"Qualité (1-10)",
  dash_date_time:"Date & Heure", dash_setup_notes:"Setup, raisonnement, leçons apprises…",
  dash_no_daily:"Aucune donnée journalière",
  journal_title:"Journal de trading", journal_logged:"trades enregistrés", journal_shown:"affichés",
  journal_new_trade:"Nouveau trade", journal_table:"Tableau", journal_calendar:"Calendrier",
  journal_filters:"Filtres", journal_clear_all:"Tout effacer", journal_replay:"Rejouer",
  journal_ai_review:"Analyse IA", journal_min_quality:"Qualité min.",
  journal_pnl_range:"Plage P&L ($)", journal_date_range:"Plage de dates",
  journal_filter_tag:"Filtrer par étiquette", journal_running_pnl:"P&L en cours",
  journal_no_trades:"Aucun trade. Appuyez sur + !",
  journal_pre_entry:"Contexte (avant entrée)", journal_in_trade:"En position",
  journal_closed:"Clôturé", journal_bars:"bougies",
  notebook_title:"Cahier quotidien", notebook_premarket:"Plan pré-marché",
  notebook_postmarket:"Bilan post-marché", notebook_mindset:"État d'esprit & Discipline",
  notebook_bias:"Biais de marché", notebook_watchlist:"Symboles à surveiller",
  notebook_watchlist_ph:"XAUUSD, UK100, EURUSD…",
  notebook_plan:"Plan de trading & niveaux clés", notebook_goals:"Objectifs du jour",
  notebook_review:"Comment s'est passée la journée ?", notebook_lessons:"Leçons apprises",
  notebook_mistakes:"Erreurs à corriger", notebook_discipline:"Discipline",
  notebook_day_summary:"Résumé du jour", notebook_no_trades:"Aucun trade ce jour",
  notebook_day_pnl:"P&L du jour", notebook_today:"Aujourd'hui",
  notebook_saving:"Enregistrement…", notebook_saved:"Enregistré",
  notebook_mindset_state:"État d'esprit du jour", notebook_poor:"Faible",
  below_avg:"Below Avg", average:"Average", good:"Good",
  notebook_excellent:"Excellent", notebook_score:"Score",
  analytics_title:"Analytiques", analytics_period:"PÉRIODE :",
  analytics_account:"COMPTE :", analytics_symbol:"SYMBOLE :",
  analytics_net_pnl:"P&L net", analytics_win_rate:"Taux de gain",
  analytics_profit_factor:"Facteur de profit", analytics_expectancy:"Espérance",
  analytics_max_dd:"Drawdown max.", analytics_avg_rr:"R:R moyen",
  analytics_total_fees:"Frais totaux", analytics_periods:"Périodes",
  analytics_profitable:"Rentable", analytics_unprofitable:"Non rentable",
  analytics_best:"Meilleur", analytics_worst:"Pire",
  analytics_equity_curve:"Courbe d'équité", analytics_outcome_dist:"Répartition des résultats",
  analytics_daily_pnl:"P&L quotidien", analytics_by_session:"Par session",
  analytics_by_pair:"Par paire", analytics_by_tf:"Par unité de temps",
  analytics_perf_pair:"Performance par paire", analytics_wr_dow:"Taux de gain par jour",
  analytics_buy_sell:"ACHAT vs VENTE", analytics_quality_pnl:"Qualité vs P&L",
  analytics_streaks:"Séries", analytics_drawdown:"Drawdown (%)",
  analytics_pnl_dist:"Distribution P&L", analytics_monthly:"Récapitulatif mensuel",
  reports_title:"Rapports avancés", reports_dimensions:"50+ dimensions",
  period_all:"Tout", period_ytd:"Depuis jan.", period_1y:"1 an",
  period_6m:"6 mois", period_3m:"3 mois", period_1m:"1 mois", period_1w:"1 semaine",
  bt_title:"Backtesting", bt_new_session:"Nouvelle session", bt_create_first:"Créer la première session",
  bt_session_name:"Nom de la session", bt_session_ph:"ex. XAUUSD London Breakout T1",
  bt_initial_capital:"Capital initial", bt_playbook:"Stratégie", bt_no_playbook:"Sans stratégie",
  bt_strategy:"Résumé de la stratégie", bt_strategy_ph:"Décrivez la stratégie testée…",
  bt_notes_ph:"Notes supplémentaires…", bt_add_trade:"Ajouter un trade", bt_save_trade:"Enregistrer le trade",
  bt_trades:"Trades", bt_equity_curve:"Courbe d'équité", bt_trade_pnl:"P&L des trades",
  bt_delete_title:"Supprimer la session ?",
  bt_delete_desc:"Cette session de backtesting et tous ses trades seront supprimés définitivement.",
  bs_title:"Courtier Sync", bs_connected_accounts:"Comptes connectés",
  bs_no_accounts:"Aucun compte connecté", bs_connect_first:"Connectez votre premier compte",
  bs_connect_another:"Connecter un autre compte", bs_manage:"Gérer",
  bs_how_to:"Comment connecter MT5", bs_choose_method:"Choisissez une méthode de connexion",
  bs_ea_connection:"Connexion EA", bs_ea_subtitle:"Expert Advisor · Temps réel",
  bs_ea_active:"Actif", bs_direct:"Identifiants directs",
  bs_direct_subtitle:"Login MT5 · Sans EA",
  bs_connecting:"Connexion à MT5…", bs_connected:"Connecté !",
  bs_failed:"Connexion échouée", bs_try_again:"Réessayer",
  bs_broker_name:"Nom du courtier", bs_broker_ph:"ex. Exness",
  bs_login:"Login compte MT5", bs_login_ph:"409913367",
  bs_server:"Serveur du courtier", bs_server_ph:"Exness-MT5Real10",
  bs_password:"Mot de passe investisseur", bs_password_ph:"••••••••",
  bs_token:"Token", bs_token_ph:"Votre token EA", bs_step:"Étape",
  bs_ea_sync:"EA TradeSylla_Sync", bs_ea_market:"EA TradeSylla_MarketData",
  bs_direct_mt5:"Connexion MT5 directe",
  calc_title:"Calculateur de taille de position", calc_rr_title:"Calculateur Risque/Récompense",
  calc_pip_title:"Calculateur de valeur pip", calc_pip_desc:"Combien vaut chaque pip en USD",
  calc_risk_title:"Gestionnaire de risque quotidien", calc_risk_desc:"Gardez votre drawdown journalier sous contrôle",
  calc_balance:"Solde du compte", calc_risk_pct:"Risque par trade",
  calc_entry:"Prix d'entrée", calc_entry_ph:"ex. 2340.50",
  calc_sl:"Stop Loss", calc_sl_ph:"ex. 2330.00",
  calc_tp:"Take Profit", calc_tp_ph:"ex. 2375.00",
  calc_win_rate:"Votre taux de gain", calc_risk_amount:"Montant à risque",
  calc_lot_size:"Taille de lot", calc_stop_dist:"Distance du stop",
  calc_pip_value:"Valeur du pip", calc_units:"Unités",
  calc_fill_all:"Remplissez tous les champs pour calculer",
  calc_fill_entry:"Remplissez entrée, SL et TP pour calculer",
  calc_fill_fields:"Remplissez les champs pour calculer",
  calc_rr_ratio:"Ratio R:R", calc_reward:"Récompense", calc_breakeven_wr:"Taux de gain seuil",
  calc_risk_dist:"Distance de risque", calc_reward_dist:"Distance de récompense",
  calc_risk_label:"Risque : $", calc_reward_label:"Récompense : $",
  calc_value_per_pip:"Valeur par pip", calc_pip_size:"Taille du pip",
  calc_instrument:"Instrument", calc_pips_count:"Nombre de pips",
  calc_market_price:"Prix actuel/marché (optionnel)", calc_market_desc:"Pour une valeur pip précise",
  calc_cross_price:"Prix actuel (paires croisées)", calc_cross_desc:"Optionnel — améliore la précision",
  calc_max_daily:"Perte quotidienne max.", calc_planned_risk:"Risque planifié aujourd'hui",
  calc_max_trades:"Trades max. autorisés", calc_risk_used:"Risque utilisé",
  calc_max_daily_risk:"Risque quotidien max.", calc_trades_today:"Trades planifiés aujourd'hui",
  pb_title:"Stratégies", pb_new:"Nouvelle stratégie", pb_create_first:"Créer la première stratégie",
  pb_delete_title:"Supprimer la stratégie ?",
  pb_delete_desc:"Cette stratégie et toutes ses données seront supprimées définitivement.",
  pb_strategy_name:"Nom de la stratégie", pb_strategy_ph:"ex. London Breakout",
  pb_category:"Catégorie", pb_status:"Statut", pb_description:"Description",
  pb_desc_ph:"Aperçu rapide de cette stratégie…",
  pb_sessions:"Sessions", pb_timeframes:"Unités de temps", pb_pairs:"Paires",
  pb_custom_pairs:"Paires/actifs personnalisés (séparés par virgule)",
  pb_custom_ph:"ex. BTCUSD, ETHUSD, TSLA",
  pb_entry_rules:"Règles d'entrée", pb_exit_rules:"Règles de sortie", pb_risk_rules:"Règles de risque",
  pb_confluences:"CONFLUENCES & SETUPS PAR DIRECTION",
  pb_long_conf:"Confluences LONG / ACHAT", pb_short_conf:"Confluences SHORT / VENTE",
  pb_screenshots:"Screenshots du setup", pb_add_screenshot:"Ajouter un screenshot",
  pb_perf_targets:"Objectifs de performance (optionnel)",
  pb_target_wr:"Taux de gain cible %", pb_target_pf:"Facteur de profit cible",
  pb_target_rr:"R:R moyen cible", pb_add_notes:"Notes supplémentaires",
  pb_target_wr_short:"TG Win", pb_target_pf_short:"TG PF",
  pb_target_rr_short:"TG R:R",
  settings_title:"Paramètres", settings_account:"Compte",
  settings_appearance:"Apparence", settings_language:"Langue",
  settings_data:"Données & Import", settings_api:"Clés API",
  settings_notif:"Notifications", settings_lang_title:"Langue d'affichage",
  settings_lang_desc:"Choisissez la langue utilisée dans toute l'application.",
  settings_lang_saved:"Langue enregistrée",
  settings_profile:"Informations du profil", settings_display_name:"Nom d'affichage",
  settings_name_ph:"Votre nom", settings_currency:"Devise",
  settings_email:"E-mail", settings_bio:"Style de trading / Bio",
  settings_free_plan:"Plan gratuit", settings_upgrade:"Passer à Pro",
  settings_upgrade_btn:"Améliorer →", settings_theme:"Thème",
  settings_custom_colors:"Couleurs personnalisées", settings_data_summary:"Résumé des données",
  settings_export:"Exporter une sauvegarde", settings_danger:"Zone dangereuse",
  settings_danger_clear:"Effacer", settings_sure:"Êtes-vous sûr ?",
  settings_notif_prefs:"Préférences de notifications",
  settings_rtl:"RTL", settings_saved:"Enregistré",
  settings_sylledge_key:"SYLLEDGE IA (Clé API Anthropic)",
  settings_key_ph:"sk-ant-api03-…", settings_key_active:"SYLLEDGE IA est actif et prêt",
  settings_user_token:"Token EA TradeSylla_Sync",
  settings_admin_token:"Token EA SYLLEDGE MarketData",
  sylledge_title:"SYLLEDGE IA", sylledge_placeholder:"Posez une question à SYLLEDGE sur votre trading…",
  sylledge_thinking:"SYLLEDGE réfléchit…", sylledge_no_playbook:"Aucune stratégie active",
  sylledge_no_insights:"Aucun insight enregistré", sylledge_market:"Graphiques de marché",
  err_load:"Échec du chargement", err_save:"Échec de l'enregistrement",
  err_not_found:"Introuvable", err_auth:"Veuillez vous reconnecter",
}

const es = {
  nav_dashboard:"Panel", nav_journal:"Diario", nav_notebook:"Cuaderno",
  nav_calendar:"Calendario", nav_analytics:"Análisis", nav_reports:"Informes",
  nav_playbook:"Estrategias", nav_sylledge:"SYLLEDGE IA", nav_backtesting:"Backtesting",
  nav_brokersync:"Sincronizar Broker", nav_settings:"Ajustes", nav_calculator:"Calculadora",
  nav_market_charts:"Gráficos", nav_admin:"Admin",
  nav_upgrade:"Actualizar a Pro", nav_live:"En vivo",
  save:"Guardar", cancel:"Cancelar", delete:"Eliminar", edit:"Editar", add:"Añadir",
  clear:"Limpiar", close:"Cerrar", confirm:"Confirmar", search:"Buscar", filter:"Filtrar",
  export:"Exportar", import:"Importar", loading:"Cargando…", no_data:"Sin datos",
  view_all:"Ver todo", show_more:"Mostrar más", done:"Listo", retry:"Reintentar",
  back:"Atrás", next:"Siguiente", yes:"Sí", no:"No", new:"Nuevo", refresh:"Actualizar",
  copy:"Copiar", copied:"¡Copiado!", connect:"Conectar",
  symbol:"Símbolo", direction:"Dirección", entry:"Entrada", exit:"Salida",
  pnl:"G/P", pips:"Pips", outcome:"Resultado", session:"Sesión",
  timeframe:"Temporalidad", quality:"Calidad", date:"Fecha", time:"Hora",
  notes:"Notas", tags:"Etiquetas", actions:"Acciones", win:"GANANCIA", loss:"PÉRDIDA",
  breakeven:"NEUTRO", buy:"COMPRA", sell:"VENTA", volume:"Volumen",
  commission:"Comisión", swap:"Swap", total:"Total", status:"Estado",
  description:"Descripción", name:"Nombre", category:"Categoría",
  dash_title:"Panel principal", dash_new_trade:"Nueva operación", dash_net_pnl:"G/P neto",
  dash_win_rate:"Tasa de acierto", dash_profit_factor:"Factor de beneficio",
  dash_expectancy:"Esperanza", dash_sylla_score:"Puntuación SYLLA",
  dash_equity_curve:"Curva de capital", dash_recent_trades:"Operaciones recientes",
  dash_activity:"Actividad reciente", dash_today:"Hoy",
  dash_heatmap:"Actividad de trading", dash_daily_pnl:"G/P diario",
  dash_log_trade:"Registrar operación", dash_no_activity:"Sin actividad. ¡Registra tu primera operación!",
  dash_no_trades:"Sin operaciones. Pulsa",
  dash_log_to_see:"Registra operaciones para ver el gráfico",
  dash_log_2_trades:"Registra 2+ operaciones para ver la puntuación",
  dash_live:"En vivo", dash_account:"CUENTA", dash_quality:"Calidad (1-10)",
  dash_date_time:"Fecha & Hora", dash_setup_notes:"Setup, razonamiento, lecciones…",
  dash_no_daily:"Sin datos diarios",
  journal_title:"Diario de trading", journal_logged:"operaciones registradas", journal_shown:"mostradas",
  journal_new_trade:"Nueva operación", journal_table:"Tabla", journal_calendar:"Calendario",
  journal_filters:"Filtros", journal_clear_all:"Limpiar todo", journal_replay:"Repetición",
  journal_ai_review:"Análisis IA", journal_min_quality:"Calidad mínima",
  journal_pnl_range:"Rango G/P ($)", journal_date_range:"Rango de fechas",
  journal_filter_tag:"Filtrar por etiqueta", journal_running_pnl:"G/P en curso",
  journal_no_trades:"Sin operaciones. ¡Pulsa +!",
  journal_pre_entry:"Contexto (antes de entrada)", journal_in_trade:"En posición",
  journal_closed:"Cerrado", journal_bars:"velas",
  notebook_title:"Cuaderno diario", notebook_premarket:"Plan pre-mercado",
  notebook_postmarket:"Revisión post-mercado", notebook_mindset:"Mentalidad & Disciplina",
  notebook_bias:"Sesgo de mercado", notebook_watchlist:"Símbolos a vigilar",
  notebook_watchlist_ph:"XAUUSD, UK100, EURUSD…",
  notebook_plan:"Plan & niveles clave", notebook_goals:"Objetivos de hoy",
  notebook_review:"¿Cómo fue el día?", notebook_lessons:"Lecciones aprendidas",
  notebook_mistakes:"Errores a corregir", notebook_discipline:"Disciplina",
  notebook_day_summary:"Resumen del día", notebook_no_trades:"Sin operaciones este día",
  notebook_day_pnl:"G/P del día", notebook_today:"Hoy",
  notebook_saving:"Guardando…", notebook_saved:"Guardado",
  notebook_mindset_state:"Mentalidad de hoy", notebook_poor:"Pobre",
  below_avg:Below Avg, below_avg:En dessous de la moyenne, below_avg:Por debajo del promedio, below_avg:أقل من المتوسط, notebook_excellent:"Excelente", notebook_score:"Puntuación",
  analytics_title:"Análisis", analytics_period:"PERÍODO:",
  analytics_account:"CUENTA:", analytics_symbol:"SÍMBOLO:",
  analytics_net_pnl:"G/P neto", analytics_win_rate:"Tasa de acierto",
  analytics_profit_factor:"Factor de beneficio", analytics_expectancy:"Esperanza",
  analytics_max_dd:"Drawdown máx.", analytics_avg_rr:"R:R medio",
  analytics_total_fees:"Comisiones totales", analytics_periods:"Períodos",
  analytics_profitable:"Rentable", analytics_unprofitable:"No rentable",
  analytics_best:"Mejor", analytics_worst:"Peor",
  analytics_equity_curve:"Curva de capital", analytics_outcome_dist:"Distribución de resultados",
  analytics_daily_pnl:"G/P diario", analytics_by_session:"Por sesión",
  analytics_by_pair:"Por par", analytics_by_tf:"Por temporalidad",
  analytics_perf_pair:"Rendimiento por par", analytics_wr_dow:"Tasa de acierto por día",
  analytics_buy_sell:"COMPRA vs VENTA", analytics_quality_pnl:"Calidad vs G/P",
  analytics_streaks:"Rachas", analytics_drawdown:"Drawdown (%)",
  analytics_pnl_dist:"Distribución G/P", analytics_monthly:"Resumen mensual",
  reports_title:"Informes avanzados", reports_dimensions:"50+ dimensiones",
  period_all:"Todo", period_ytd:"Este año", period_1y:"1 año",
  period_6m:"6 meses", period_3m:"3 meses", period_1m:"1 mes", period_1w:"1 semana",
  bt_title:"Backtesting", bt_new_session:"Nueva sesión", bt_create_first:"Crear primera sesión",
  bt_session_name:"Nombre de sesión", bt_session_ph:"ej. XAUUSD London Breakout T1",
  bt_initial_capital:"Capital inicial", bt_playbook:"Estrategia", bt_no_playbook:"Sin estrategia",
  bt_strategy:"Resumen de estrategia", bt_strategy_ph:"Describe la estrategia probada…",
  bt_notes_ph:"Notas adicionales…", bt_add_trade:"Añadir operación", bt_save_trade:"Guardar operación",
  bt_trades:"Operaciones", bt_equity_curve:"Curva de capital", bt_trade_pnl:"G/P de operaciones",
  bt_delete_title:"¿Eliminar sesión?",
  bt_delete_desc:"Esta sesión de backtesting y todas sus operaciones se eliminarán permanentemente.",
  bs_title:"Sincronizar Broker", bs_connected_accounts:"Cuentas conectadas",
  bs_no_accounts:"Sin cuentas conectadas", bs_connect_first:"Conecta tu primera cuenta",
  bs_connect_another:"Conectar otra cuenta", bs_manage:"Gestionar",
  bs_how_to:"Cómo conectar MT5", bs_choose_method:"Elige un método de conexión",
  bs_ea_connection:"Conexión EA", bs_ea_subtitle:"Expert Advisor · Tiempo real",
  bs_ea_active:"Activo", bs_direct:"Credenciales directas",
  bs_direct_subtitle:"Login MT5 · Sin EA",
  bs_connecting:"Conectando a MT5…", bs_connected:"¡Conectado!",
  bs_failed:"Conexión fallida", bs_try_again:"Reintentar",
  bs_broker_name:"Nombre del broker", bs_broker_ph:"ej. Exness",
  bs_login:"Login cuenta MT5", bs_login_ph:"409913367",
  bs_server:"Servidor del broker", bs_server_ph:"Exness-MT5Real10",
  bs_password:"Contraseña inversión", bs_password_ph:"••••••••",
  bs_token:"Token", bs_token_ph:"Tu token EA", bs_step:"Paso",
  bs_ea_sync:"EA TradeSylla_Sync", bs_ea_market:"EA TradeSylla_MarketData",
  bs_direct_mt5:"Conexión MT5 directa",
  calc_title:"Calculadora de tamaño de posición", calc_rr_title:"Calculadora Riesgo/Recompensa",
  calc_pip_title:"Calculadora de valor pip", calc_pip_desc:"Cuánto vale cada pip en USD",
  calc_risk_title:"Gestor de riesgo diario", calc_risk_desc:"Controla tu drawdown diario",
  calc_balance:"Saldo de la cuenta", calc_risk_pct:"Riesgo por operación",
  calc_entry:"Precio de entrada", calc_entry_ph:"ej. 2340.50",
  calc_sl:"Stop Loss", calc_sl_ph:"ej. 2330.00",
  calc_tp:"Take Profit", calc_tp_ph:"ej. 2375.00",
  calc_win_rate:"Tu tasa de acierto", calc_risk_amount:"Importe arriesgado",
  calc_lot_size:"Tamaño de lote", calc_stop_dist:"Distancia del stop",
  calc_pip_value:"Valor del pip", calc_units:"Unidades",
  calc_fill_all:"Completa todos los campos para calcular",
  calc_fill_entry:"Completa entrada, SL y TP para calcular",
  calc_fill_fields:"Completa los campos para calcular",
  calc_rr_ratio:"Ratio R:R", calc_reward:"Recompensa", calc_breakeven_wr:"Tasa de equilibrio",
  calc_risk_dist:"Distancia de riesgo", calc_reward_dist:"Distancia de recompensa",
  calc_risk_label:"Riesgo: $", calc_reward_label:"Recompensa: $",
  calc_value_per_pip:"Valor por pip", calc_pip_size:"Tamaño del pip",
  calc_instrument:"Instrumento", calc_pips_count:"Número de pips",
  calc_market_price:"Precio actual/mercado (opcional)", calc_market_desc:"Para valor pip preciso",
  calc_cross_price:"Precio actual (pares cruzados)", calc_cross_desc:"Opcional — mejora la precisión",
  calc_max_daily:"Pérdida diaria máx.", calc_planned_risk:"Riesgo planificado hoy",
  calc_max_trades:"Máx. operaciones permitidas", calc_risk_used:"Riesgo usado",
  calc_max_daily_risk:"Riesgo diario máx.", calc_trades_today:"Operaciones planificadas hoy",
  pb_title:"Estrategias", pb_new:"Nueva estrategia", pb_create_first:"Crear primera estrategia",
  pb_delete_title:"¿Eliminar estrategia?",
  pb_delete_desc:"Esta estrategia y todos sus datos se eliminarán permanentemente.",
  pb_strategy_name:"Nombre de la estrategia", pb_strategy_ph:"ej. London Breakout",
  pb_category:"Categoría", pb_status:"Estado", pb_description:"Descripción",
  pb_desc_ph:"Resumen breve de esta estrategia…",
  pb_sessions:"Sesiones", pb_timeframes:"Temporalidades", pb_pairs:"Pares",
  pb_custom_pairs:"Pares/activos personalizados (separados por coma)",
  pb_custom_ph:"ej. BTCUSD, ETHUSD, TSLA",
  pb_entry_rules:"Reglas de entrada", pb_exit_rules:"Reglas de salida", pb_risk_rules:"Reglas de riesgo",
  pb_confluences:"CONFLUENCIAS & SETUPS POR DIRECCIÓN",
  pb_long_conf:"Confluencias LARGO / COMPRA", pb_short_conf:"Confluencias CORTO / VENTA",
  pb_screenshots:"Capturas del setup", pb_add_screenshot:"Añadir captura",
  pb_perf_targets:"Objetivos de rendimiento (opcional)",
  pb_target_wr:"Tasa de acierto objetivo %", pb_target_pf:"Factor de beneficio objetivo",
  pb_target_rr:"R:R medio objetivo", pb_add_notes:"Notas adicionales",
  pb_target_wr_short:"Obj. TA", pb_target_pf_short:"Obj. FB",
  pb_target_rr_short:"Obj. R:R",
  settings_title:"Ajustes", settings_account:"Cuenta",
  settings_appearance:"Apariencia", settings_language:"Idioma",
  settings_data:"Datos & Importación", settings_api:"Claves API",
  settings_notif:"Notificaciones", settings_lang_title:"Idioma de la app",
  settings_lang_desc:"Elige el idioma usado en toda la aplicación.",
  settings_lang_saved:"Idioma guardado",
  settings_profile:"Información del perfil", settings_display_name:"Nombre de visualización",
  settings_name_ph:"Tu nombre", settings_currency:"Divisa",
  settings_email:"Correo electrónico", settings_bio:"Estilo de trading / Bio",
  settings_free_plan:"Plan gratuito", settings_upgrade:"Actualizar a Pro",
  settings_upgrade_btn:"Mejorar →", settings_theme:"Tema",
  settings_custom_colors:"Colores personalizados", settings_data_summary:"Resumen de datos",
  settings_export:"Exportar copia de seguridad", settings_danger:"Zona peligrosa",
  settings_danger_clear:"Limpiar", settings_sure:"¿Estás seguro?",
  settings_notif_prefs:"Preferencias de notificaciones",
  settings_rtl:"RTL", settings_saved:"Guardado",
  settings_sylledge_key:"SYLLEDGE IA (Clave API Anthropic)",
  settings_key_ph:"sk-ant-api03-…", settings_key_active:"SYLLEDGE IA activo y listo",
  settings_user_token:"Token EA TradeSylla_Sync",
  settings_admin_token:"Token EA SYLLEDGE MarketData",
  sylledge_title:"SYLLEDGE IA", sylledge_placeholder:"Pregunta a SYLLEDGE sobre tu trading…",
  sylledge_thinking:"SYLLEDGE está pensando…", sylledge_no_playbook:"Sin estrategia activa",
  sylledge_no_insights:"Sin insights guardados", sylledge_market:"Gráficos de mercado",
  err_load:"Error al cargar datos", err_save:"Error al guardar",
  err_not_found:"No encontrado", err_auth:"Por favor inicia sesión de nuevo",
}

const ar = {
  nav_dashboard:"لوحة التحكم", nav_journal:"سجل التداول", nav_notebook:"الدفتر",
  nav_calendar:"التقويم", nav_analytics:"التحليلات", nav_reports:"التقارير",
  nav_playbook:"الاستراتيجيات", nav_sylledge:"SYLLEDGE AI", nav_backtesting:"الاختبار التاريخي",
  nav_brokersync:"مزامنة الوسيط", nav_settings:"الإعدادات", nav_calculator:"الحاسبة",
  nav_market_charts:"الرسوم البيانية", nav_admin:"الإدارة",
  nav_upgrade:"الترقية إلى Pro", nav_live:"مباشر",
  save:"حفظ", cancel:"إلغاء", delete:"حذف", edit:"تعديل", add:"إضافة",
  clear:"مسح", close:"إغلاق", confirm:"تأكيد", search:"بحث", filter:"تصفية",
  export:"تصدير", import:"استيراد", loading:"جاري التحميل…", no_data:"لا توجد بيانات",
  view_all:"عرض الكل", show_more:"عرض المزيد", done:"تم", retry:"إعادة المحاولة",
  back:"رجوع", next:"التالي", yes:"نعم", no:"لا", new:"جديد", refresh:"تحديث",
  copy:"نسخ", copied:"تم النسخ!", connect:"اتصال",
  symbol:"الرمز", direction:"الاتجاه", entry:"الدخول", exit:"الخروج",
  pnl:"الربح/الخسارة", pips:"نقاط", outcome:"النتيجة", session:"الجلسة",
  timeframe:"الإطار الزمني", quality:"الجودة", date:"التاريخ", time:"الوقت",
  notes:"ملاحظات", tags:"الوسوم", actions:"إجراءات", win:"ربح", loss:"خسارة",
  breakeven:"متعادل", buy:"شراء", sell:"بيع", volume:"الحجم",
  commission:"العمولة", swap:"السواب", total:"المجموع", status:"الحالة",
  description:"الوصف", name:"الاسم", category:"الفئة",
  dash_title:"لوحة التحكم", dash_new_trade:"صفقة جديدة", dash_net_pnl:"صافي الربح/الخسارة",
  dash_win_rate:"نسبة الفوز", dash_profit_factor:"معامل الربح",
  dash_expectancy:"التوقع الرياضي", dash_sylla_score:"نقاط SYLLA",
  dash_equity_curve:"منحنى رأس المال", dash_recent_trades:"الصفقات الأخيرة",
  dash_activity:"النشاط الأخير", dash_today:"اليوم",
  dash_heatmap:"نشاط التداول", dash_daily_pnl:"الربح/الخسارة اليومي",
  dash_log_trade:"تسجيل صفقة", dash_no_activity:"لا نشاط. سجّل صفقتك الأولى!",
  dash_no_trades:"لا صفقات. اضغط",
  dash_log_to_see:"سجّل صفقات لرؤية الرسم البياني",
  dash_log_2_trades:"سجّل صفقتين+ لرؤية النقاط",
  dash_live:"مباشر", dash_account:"الحساب", dash_quality:"الجودة (1-10)",
  dash_date_time:"التاريخ والوقت", dash_setup_notes:"الإعداد، المنطق، الدروس…",
  dash_no_daily:"لا بيانات يومية",
  journal_title:"سجل التداول", journal_logged:"صفقة مسجلة", journal_shown:"معروضة",
  journal_new_trade:"صفقة جديدة", journal_table:"جدول", journal_calendar:"تقويم",
  journal_filters:"الفلاتر", journal_clear_all:"مسح الكل", journal_replay:"إعادة التشغيل",
  journal_ai_review:"مراجعة الذكاء الاصطناعي", journal_min_quality:"أدنى جودة",
  journal_pnl_range:"نطاق الربح/الخسارة ($)", journal_date_range:"نطاق التاريخ",
  journal_filter_tag:"فلترة بالوسم", journal_running_pnl:"الربح/الخسارة الجاري",
  journal_no_trades:"لا توجد صفقات. اضغط +!",
  journal_pre_entry:"سياق (قبل الدخول)", journal_in_trade:"في الصفقة",
  journal_closed:"مغلق", journal_bars:"شمعة",
  notebook_title:"الدفتر اليومي", notebook_premarket:"خطة ما قبل السوق",
  notebook_postmarket:"مراجعة ما بعد السوق", notebook_mindset:"الحالة الذهنية والانضباط",
  notebook_bias:"توجه السوق", notebook_watchlist:"الرموز المراقبة",
  notebook_watchlist_ph:"XAUUSD, UK100, EURUSD…",
  notebook_plan:"خطة التداول والمستويات الرئيسية", notebook_goals:"أهداف اليوم",
  notebook_review:"كيف كان اليوم؟", notebook_lessons:"الدروس المستفادة",
  notebook_mistakes:"الأخطاء للتصحيح", notebook_discipline:"الانضباط",
  notebook_day_summary:"ملخص اليوم", notebook_no_trades:"لا توجد صفقات هذا اليوم",
  notebook_day_pnl:"ربح/خسارة اليوم", notebook_today:"اليوم",
  notebook_saving:"جاري الحفظ…", notebook_saved:"تم الحفظ",
  notebook_mindset_state:"الحالة الذهنية اليوم", notebook_poor:"ضعيف",
  below_avg:Below Avg, below_avg:En dessous de la moyenne, below_avg:Por debajo del promedio, below_avg:أقل من المتوسط, notebook_excellent:"ممتاز", notebook_score:"النقاط",
  analytics_title:"التحليلات", analytics_period:"الفترة:",
  analytics_account:"الحساب:", analytics_symbol:"الرمز:",
  analytics_net_pnl:"صافي الربح/الخسارة", analytics_win_rate:"نسبة الفوز",
  analytics_profit_factor:"معامل الربح", analytics_expectancy:"التوقع الرياضي",
  analytics_max_dd:"أقصى تراجع", analytics_avg_rr:"متوسط R:R",
  analytics_total_fees:"إجمالي الرسوم", analytics_periods:"الفترات",
  analytics_profitable:"مربح", analytics_unprofitable:"غير مربح",
  analytics_best:"الأفضل", analytics_worst:"الأسوأ",
  analytics_equity_curve:"منحنى رأس المال", analytics_outcome_dist:"توزيع النتائج",
  analytics_daily_pnl:"الربح/الخسارة اليومي", analytics_by_session:"حسب الجلسة",
  analytics_by_pair:"حسب الزوج", analytics_by_tf:"حسب الإطار الزمني",
  analytics_perf_pair:"الأداء حسب الزوج", analytics_wr_dow:"نسبة الفوز حسب اليوم",
  analytics_buy_sell:"شراء مقابل بيع", analytics_quality_pnl:"الجودة مقابل الربح/الخسارة",
  analytics_streaks:"التسلسلات", analytics_drawdown:"التراجع (%)",
  analytics_pnl_dist:"توزيع الربح/الخسارة", analytics_monthly:"الملخص الشهري",
  reports_title:"تقارير متقدمة", reports_dimensions:"أكثر من 50 بُعداً",
  period_all:"الكل", period_ytd:"هذا العام", period_1y:"سنة",
  period_6m:"6 أشهر", period_3m:"3 أشهر", period_1m:"شهر", period_1w:"أسبوع",
  bt_title:"الاختبار التاريخي", bt_new_session:"جلسة جديدة", bt_create_first:"إنشاء أول جلسة",
  bt_session_name:"اسم الجلسة", bt_session_ph:"مثال: XAUUSD London Breakout",
  bt_initial_capital:"رأس المال الأولي", bt_playbook:"الاستراتيجية", bt_no_playbook:"بدون استراتيجية",
  bt_strategy:"ملخص الاستراتيجية", bt_strategy_ph:"صف الاستراتيجية المختبرة…",
  bt_notes_ph:"ملاحظات إضافية…", bt_add_trade:"إضافة صفقة", bt_save_trade:"حفظ الصفقة",
  bt_trades:"الصفقات", bt_equity_curve:"منحنى رأس المال", bt_trade_pnl:"ربح/خسارة الصفقات",
  bt_delete_title:"حذف الجلسة؟",
  bt_delete_desc:"ستُحذف هذه الجلسة وجميع صفقاتها نهائياً.",
  bs_title:"مزامنة الوسيط", bs_connected_accounts:"الحسابات المتصلة",
  bs_no_accounts:"لا توجد حسابات متصلة", bs_connect_first:"اتصل بحسابك الأول",
  bs_connect_another:"اتصال بحساب آخر", bs_manage:"إدارة",
  bs_how_to:"كيفية الاتصال بـ MT5", bs_choose_method:"اختر طريقة الاتصال",
  bs_ea_connection:"اتصال EA", bs_ea_subtitle:"مستشار خبير · في الوقت الفعلي",
  bs_ea_active:"نشط", bs_direct:"بيانات الاعتماد المباشرة",
  bs_direct_subtitle:"تسجيل دخول MT5 · بدون EA",
  bs_connecting:"جاري الاتصال بـ MT5…", bs_connected:"تم الاتصال!",
  bs_failed:"فشل الاتصال", bs_try_again:"إعادة المحاولة",
  bs_broker_name:"اسم الوسيط", bs_broker_ph:"مثال: Exness",
  bs_login:"رقم حساب MT5", bs_login_ph:"409913367",
  bs_server:"خادم الوسيط", bs_server_ph:"Exness-MT5Real10",
  bs_password:"كلمة مرور المستثمر", bs_password_ph:"••••••••",
  bs_token:"الرمز المميز", bs_token_ph:"رمز EA الخاص بك", bs_step:"خطوة",
  bs_ea_sync:"EA TradeSylla_Sync", bs_ea_market:"EA TradeSylla_MarketData",
  bs_direct_mt5:"اتصال MT5 مباشر",
  calc_title:"حاسبة حجم المركز", calc_rr_title:"حاسبة المخاطرة/المكافأة",
  calc_pip_title:"حاسبة قيمة النقطة", calc_pip_desc:"كم تساوي كل نقطة بالدولار",
  calc_risk_title:"مدير المخاطر اليومي", calc_risk_desc:"حافظ على تراجعك اليومي تحت السيطرة",
  calc_balance:"رصيد الحساب", calc_risk_pct:"المخاطرة لكل صفقة",
  calc_entry:"سعر الدخول", calc_entry_ph:"مثال: 2340.50",
  calc_sl:"وقف الخسارة", calc_sl_ph:"مثال: 2330.00",
  calc_tp:"هدف الربح", calc_tp_ph:"مثال: 2375.00",
  calc_win_rate:"نسبة فوزك", calc_risk_amount:"مبلغ المخاطرة",
  calc_lot_size:"حجم اللوت", calc_stop_dist:"مسافة الوقف",
  calc_pip_value:"قيمة النقطة", calc_units:"الوحدات",
  calc_fill_all:"أدخل جميع البيانات للحساب",
  calc_fill_entry:"أدخل الدخول، وقف الخسارة، والهدف للحساب",
  calc_fill_fields:"أدخل البيانات للحساب",
  calc_rr_ratio:"نسبة R:R", calc_reward:"المكافأة", calc_breakeven_wr:"نسبة التعادل",
  calc_risk_dist:"مسافة المخاطرة", calc_reward_dist:"مسافة المكافأة",
  calc_risk_label:"المخاطرة: $", calc_reward_label:"المكافأة: $",
  calc_value_per_pip:"القيمة لكل نقطة", calc_pip_size:"حجم النقطة",
  calc_instrument:"الأداة المالية", calc_pips_count:"عدد النقاط",
  calc_market_price:"السعر الحالي/السوق (اختياري)", calc_market_desc:"لقيمة نقطة دقيقة",
  calc_cross_price:"السعر الحالي (للأزواج المتقاطعة)", calc_cross_desc:"اختياري — يحسّن الدقة",
  calc_max_daily:"أقصى خسارة يومية", calc_planned_risk:"المخاطرة المخططة اليوم",
  calc_max_trades:"أقصى عدد صفقات مسموح", calc_risk_used:"المخاطرة المستخدمة",
  calc_max_daily_risk:"أقصى مخاطرة يومية", calc_trades_today:"الصفقات المخططة اليوم",
  pb_title:"الاستراتيجيات", pb_new:"استراتيجية جديدة", pb_create_first:"إنشاء أول استراتيجية",
  pb_delete_title:"حذف الاستراتيجية؟",
  pb_delete_desc:"ستُحذف هذه الاستراتيجية وجميع بياناتها نهائياً.",
  pb_strategy_name:"اسم الاستراتيجية", pb_strategy_ph:"مثال: London Breakout",
  pb_category:"الفئة", pb_status:"الحالة", pb_description:"الوصف",
  pb_desc_ph:"نظرة عامة موجزة على هذه الاستراتيجية…",
  pb_sessions:"الجلسات", pb_timeframes:"الأطر الزمنية", pb_pairs:"الأزواج",
  pb_custom_pairs:"أزواج/أصول مخصصة (مفصولة بفاصلة)",
  pb_custom_ph:"مثال: BTCUSD, ETHUSD, TSLA",
  pb_entry_rules:"قواعد الدخول", pb_exit_rules:"قواعد الخروج", pb_risk_rules:"قواعد المخاطرة",
  pb_confluences:"التقاطعات والإعدادات حسب الاتجاه",
  pb_long_conf:"تقاطعات الشراء (LONG)", pb_short_conf:"تقاطعات البيع (SHORT)",
  pb_screenshots:"لقطات الإعداد", pb_add_screenshot:"إضافة لقطة",
  pb_perf_targets:"أهداف الأداء (اختياري)",
  pb_target_wr:"نسبة فوز مستهدفة %", pb_target_pf:"معامل ربح مستهدف",
  pb_target_rr:"متوسط R:R مستهدف", pb_add_notes:"ملاحظات إضافية",
  pb_target_wr_short:"هدف WR", pb_target_pf_short:"هدف PF",
  pb_target_rr_short:"هدف R:R",
  settings_title:"الإعدادات", settings_account:"الحساب",
  settings_appearance:"المظهر", settings_language:"اللغة",
  settings_data:"البيانات والاستيراد", settings_api:"مفاتيح API",
  settings_notif:"الإشعارات", settings_lang_title:"لغة التطبيق",
  settings_lang_desc:"اختر اللغة المستخدمة في جميع أنحاء التطبيق.",
  settings_lang_saved:"تم حفظ اللغة",
  settings_profile:"معلومات الملف الشخصي", settings_display_name:"اسم العرض",
  settings_name_ph:"اسمك", settings_currency:"العملة",
  settings_email:"البريد الإلكتروني", settings_bio:"أسلوب التداول / نبذة",
  settings_free_plan:"الخطة المجانية", settings_upgrade:"الترقية إلى Pro",
  settings_upgrade_btn:"ترقية →", settings_theme:"السمة",
  settings_custom_colors:"ألوان مخصصة", settings_data_summary:"ملخص البيانات",
  settings_export:"تصدير نسخة احتياطية", settings_danger:"المنطقة الخطرة",
  settings_danger_clear:"مسح", settings_sure:"هل أنت متأكد؟",
  settings_notif_prefs:"تفضيلات الإشعارات",
  settings_rtl:"RTL", settings_saved:"محفوظ",
  settings_sylledge_key:"SYLLEDGE AI (مفتاح API Anthropic)",
  settings_key_ph:"sk-ant-api03-…", settings_key_active:"SYLLEDGE AI نشط وجاهز",
  settings_user_token:"رمز EA TradeSylla_Sync",
  settings_admin_token:"رمز EA SYLLEDGE MarketData",
  sylledge_title:"SYLLEDGE AI", sylledge_placeholder:"اسأل SYLLEDGE أي شيء عن تداولك…",
  sylledge_thinking:"SYLLEDGE يفكر…", sylledge_no_playbook:"لا توجد استراتيجية نشطة",
  sylledge_no_insights:"لا توجد رؤى محفوظة", sylledge_market:"رسوم السوق البياني",
  err_load:"فشل في تحميل البيانات", err_save:"فشل في الحفظ",
  err_not_found:"غير موجود", err_auth:"يرجى تسجيل الدخول مجدداً",
}

export const LANGUAGES = [
  { code:"en", label:"English",  flag:"🇬🇧", dir:"ltr" },
  { code:"fr", label:"Français", flag:"🇫🇷", dir:"ltr" },
  { code:"es", label:"Español",  flag:"🇪🇸", dir:"ltr" },
  { code:"ar", label:"العربية",  flag:"🇸🇦", dir:"rtl" },
]

const DICTS = { en, fr, es, ar }

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() =>
    localStorage.getItem("ts_lang") || "en"
  )

  const setLang = (code) => {
    localStorage.setItem("ts_lang", code)
    setLangState(code)
    const info = LANGUAGES.find(l => l.code === code)
    document.documentElement.setAttribute("dir", info?.dir || "ltr")
    document.documentElement.setAttribute("lang", code)
  }

  useEffect(() => {
    const info = LANGUAGES.find(l => l.code === lang)
    document.documentElement.setAttribute("dir", info?.dir || "ltr")
    document.documentElement.setAttribute("lang", lang)
  }, [])

  const t = (key, fallback) => {
    const dict = DICTS[lang] || DICTS.en
    return dict[key] ?? DICTS.en[key] ?? fallback ?? key
  }

  const dir = LANGUAGES.find(l => l.code === lang)?.dir || "ltr"

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider")
  return ctx
}
