// src/lib/LanguageContext.jsx
// Lightweight i18n — no external deps
// Supports: English, Français, Español, العربية
// Usage: const { t, lang, setLang, dir } = useLanguage()

import { createContext, useContext, useState, useEffect } from "react"

// ─── Translation dictionaries ─────────────────────────────────────────────────

const en = {
  // Navigation
  nav_dashboard:    "Dashboard",
  nav_journal:      "Journal",
  nav_notebook:     "Notebook",
  nav_calendar:     "Calendar",
  nav_analytics:    "Analytics",
  nav_reports:      "Reports",
  nav_playbook:     "Playbook",
  nav_sylledge:     "SYLLEDGE AI",
  nav_backtesting:  "Backtesting",
  nav_brokersync:   "Broker Sync",
  nav_settings:     "Settings",
  nav_market_charts:"Market Charts",
  nav_admin:        "Admin Panel",
  nav_upgrade:      "Upgrade to Pro",
  nav_live:         "Live",

  // Common actions
  save:             "Save",
  cancel:           "Cancel",
  delete:           "Delete",
  edit:             "Edit",
  add:              "Add",
  clear:            "Clear",
  close:            "Close",
  confirm:          "Confirm",
  search:           "Search",
  filter:           "Filter",
  export:           "Export",
  import:           "Import",
  loading:          "Loading…",
  no_data:          "No data yet",
  view_all:         "View All",
  show_more:        "Show more",
  done:             "Done",
  retry:            "Retry again",
  back:             "Back",
  next:             "Next",
  yes:              "Yes",
  no:               "No",
  new:              "New",

  // Common labels
  symbol:           "Symbol",
  direction:        "Direction",
  entry:            "Entry",
  exit:             "Exit",
  pnl:              "P&L",
  pips:             "Pips",
  outcome:          "Outcome",
  session:          "Session",
  timeframe:        "Timeframe",
  quality:          "Quality",
  date:             "Date",
  time:             "Time",
  notes:            "Notes",
  tags:             "Tags",
  actions:          "Actions",
  win:              "WIN",
  loss:             "LOSS",
  breakeven:        "BREAKEVEN",
  buy:              "BUY",
  sell:             "SELL",
  volume:           "Volume",
  commission:       "Commission",
  swap:             "Swap",
  total:            "Total",

  // Dashboard
  dash_title:           "Dashboard",
  dash_new_trade:       "New Trade",
  dash_net_pnl:         "Net P&L",
  dash_win_rate:        "Win Rate",
  dash_profit_factor:   "Profit Factor",
  dash_expectancy:      "Expectancy",
  dash_sylla_score:     "SYLLA Score",
  dash_equity_curve:    "Equity Curve",
  dash_recent_trades:   "Recent Trades",
  dash_activity:        "Activity Feed",
  dash_today:           "Today",
  dash_heatmap:         "Trading Activity",

  // Journal
  journal_title:        "Trade Journal",
  journal_logged:       "trades logged",
  journal_shown:        "shown",
  journal_new_trade:    "New Trade",
  journal_table:        "Table",
  journal_calendar:     "Calendar",
  journal_filters:      "Filters",
  journal_clear_all:    "Clear all",
  journal_replay:       "Replay",
  journal_ai_review:    "AI Review",
  journal_min_quality:  "Min Quality",
  journal_pnl_range:    "P&L Range ($)",
  journal_date_range:   "Date Range",
  journal_filter_tag:   "Filter by Tag",
  journal_running_pnl:  "Running P&L",
  journal_no_trades:    "No trades yet. Hit the + button!",
  journal_pre_entry:    "Context (pre-entry)",
  journal_in_trade:     "In trade",
  journal_closed:       "Closed",
  journal_bars:         "bars",

  // Notebook
  notebook_title:       "Daily Notebook",
  notebook_premarket:   "Pre-Market Plan",
  notebook_postmarket:  "Post-Market Review",
  notebook_mindset:     "Mindset & Discipline",
  notebook_bias:        "Market Bias",
  notebook_watchlist:   "Symbols to Watch",
  notebook_plan:        "Trading Plan & Key Levels",
  notebook_goals:       "Goals for Today",
  notebook_review:      "How did the day go?",
  notebook_lessons:     "Lessons Learned",
  notebook_mistakes:    "Mistakes to Fix",
  notebook_discipline:  "Rule Discipline",
  notebook_day_summary: "Day Summary",
  notebook_no_trades:   "No trades this day",
  notebook_day_pnl:     "Day P&L",
  notebook_today:       "Today",
  notebook_saving:      "Saving…",
  notebook_saved:       "Saved",

  // Analytics / Reports
  analytics_title:      "Analytics",
  reports_title:        "Advanced Reports",
  reports_dimensions:   "50+ dimensions",
  period_all:           "All Time",
  period_ytd:           "YTD",
  period_1y:            "1 Year",
  period_6m:            "6 Months",
  period_3m:            "3 Months",
  period_1m:            "1 Month",
  period_1w:            "1 Week",

  // Settings
  settings_title:       "Settings",
  settings_account:     "Account",
  settings_appearance:  "Appearance",
  settings_language:    "Language",
  settings_data:        "Data & Import",
  settings_api:         "API Keys",
  settings_notif:       "Notifications",
  settings_lang_title:  "Display Language",
  settings_lang_desc:   "Choose the language used across the entire app.",
  settings_lang_saved:  "Language saved",

  // BrokerSync
  broker_title:         "Broker Sync",
  broker_connect:       "Connect & Import Trades",
  broker_connected:     "Connected!",
  broker_failed:        "Connection Failed",
  broker_login:         "MT5 Account Login",
  broker_server:        "Broker Server",
  broker_password:      "Investor Password",
  broker_name:          "Broker Name",
  broker_no_accounts:   "No accounts connected yet",

  // SYLLEDGE
  sylledge_placeholder: "Ask SYLLEDGE anything about your trading…",
  sylledge_thinking:    "SYLLEDGE is thinking…",

  // Errors
  err_load:             "Failed to load data",
  err_save:             "Failed to save",
  err_not_found:        "Not found",
  err_auth:             "Please log in again",
}

const fr = {
  // Navigation
  nav_dashboard:    "Tableau de bord",
  nav_journal:      "Journal",
  nav_notebook:     "Cahier",
  nav_calendar:     "Calendrier",
  nav_analytics:    "Analytiques",
  nav_reports:      "Rapports",
  nav_playbook:     "Stratégies",
  nav_sylledge:     "SYLLEDGE IA",
  nav_backtesting:  "Backtesting",
  nav_brokersync:   "Courtier Sync",
  nav_settings:     "Paramètres",
  nav_market_charts:"Graphiques",
  nav_admin:        "Admin",
  nav_upgrade:      "Passer à Pro",
  nav_live:         "En direct",

  save:             "Enregistrer",
  cancel:           "Annuler",
  delete:           "Supprimer",
  edit:             "Modifier",
  add:              "Ajouter",
  clear:            "Effacer",
  close:            "Fermer",
  confirm:          "Confirmer",
  search:           "Rechercher",
  filter:           "Filtrer",
  export:           "Exporter",
  import:           "Importer",
  loading:          "Chargement…",
  no_data:          "Aucune donnée",
  view_all:         "Tout voir",
  show_more:        "Afficher plus",
  done:             "Terminé",
  retry:            "Réessayer",
  back:             "Retour",
  next:             "Suivant",
  yes:              "Oui",
  no:               "Non",
  new:              "Nouveau",

  symbol:           "Symbole",
  direction:        "Direction",
  entry:            "Entrée",
  exit:             "Sortie",
  pnl:              "P&L",
  pips:             "Pips",
  outcome:          "Résultat",
  session:          "Session",
  timeframe:        "Unité de temps",
  quality:          "Qualité",
  date:             "Date",
  time:             "Heure",
  notes:            "Notes",
  tags:             "Étiquettes",
  actions:          "Actions",
  win:              "GAIN",
  loss:             "PERTE",
  breakeven:        "NEUTRE",
  buy:              "ACHAT",
  sell:             "VENTE",
  volume:           "Volume",
  commission:       "Commission",
  swap:             "Swap",
  total:            "Total",

  dash_title:           "Tableau de bord",
  dash_new_trade:       "Nouveau trade",
  dash_net_pnl:         "P&L net",
  dash_win_rate:        "Taux de gain",
  dash_profit_factor:   "Facteur de profit",
  dash_expectancy:      "Espérance",
  dash_sylla_score:     "Score SYLLA",
  dash_equity_curve:    "Courbe d'équité",
  dash_recent_trades:   "Trades récents",
  dash_activity:        "Activité récente",
  dash_today:           "Aujourd'hui",
  dash_heatmap:         "Activité de trading",

  journal_title:        "Journal de trading",
  journal_logged:       "trades enregistrés",
  journal_shown:        "affichés",
  journal_new_trade:    "Nouveau trade",
  journal_table:        "Tableau",
  journal_calendar:     "Calendrier",
  journal_filters:      "Filtres",
  journal_clear_all:    "Tout effacer",
  journal_replay:       "Rejouer",
  journal_ai_review:    "Analyse IA",
  journal_min_quality:  "Qualité min.",
  journal_pnl_range:    "Plage P&L ($)",
  journal_date_range:   "Plage de dates",
  journal_filter_tag:   "Filtrer par étiquette",
  journal_running_pnl:  "P&L en cours",
  journal_no_trades:    "Aucun trade. Appuyez sur + !",
  journal_pre_entry:    "Contexte (avant entrée)",
  journal_in_trade:     "En position",
  journal_closed:       "Clôturé",
  journal_bars:         "bougies",

  notebook_title:       "Cahier quotidien",
  notebook_premarket:   "Plan pré-marché",
  notebook_postmarket:  "Bilan post-marché",
  notebook_mindset:     "État d'esprit & Discipline",
  notebook_bias:        "Biais de marché",
  notebook_watchlist:   "Symboles à surveiller",
  notebook_plan:        "Plan de trading & niveaux clés",
  notebook_goals:       "Objectifs du jour",
  notebook_review:      "Comment s'est passée la journée ?",
  notebook_lessons:     "Leçons apprises",
  notebook_mistakes:    "Erreurs à corriger",
  notebook_discipline:  "Discipline",
  notebook_day_summary: "Résumé du jour",
  notebook_no_trades:   "Aucun trade ce jour",
  notebook_day_pnl:     "P&L du jour",
  notebook_today:       "Aujourd'hui",
  notebook_saving:      "Enregistrement…",
  notebook_saved:       "Enregistré",

  analytics_title:      "Analytiques",
  reports_title:        "Rapports avancés",
  reports_dimensions:   "50+ dimensions",
  period_all:           "Tout",
  period_ytd:           "Depuis jan.",
  period_1y:            "1 an",
  period_6m:            "6 mois",
  period_3m:            "3 mois",
  period_1m:            "1 mois",
  period_1w:            "1 semaine",

  settings_title:       "Paramètres",
  settings_account:     "Compte",
  settings_appearance:  "Apparence",
  settings_language:    "Langue",
  settings_data:        "Données & Import",
  settings_api:         "Clés API",
  settings_notif:       "Notifications",
  settings_lang_title:  "Langue d'affichage",
  settings_lang_desc:   "Choisissez la langue utilisée dans toute l'application.",
  settings_lang_saved:  "Langue enregistrée",

  broker_title:         "Synchronisation courtier",
  broker_connect:       "Connecter & Importer",
  broker_connected:     "Connecté !",
  broker_failed:        "Connexion échouée",
  broker_login:         "Numéro de compte MT5",
  broker_server:        "Serveur du courtier",
  broker_password:      "Mot de passe investisseur",
  broker_name:          "Nom du courtier",
  broker_no_accounts:   "Aucun compte connecté",

  sylledge_placeholder: "Posez une question à SYLLEDGE sur votre trading…",
  sylledge_thinking:    "SYLLEDGE réfléchit…",

  err_load:             "Échec du chargement",
  err_save:             "Échec de l'enregistrement",
  err_not_found:        "Introuvable",
  err_auth:             "Veuillez vous reconnecter",
}

const es = {
  nav_dashboard:    "Panel",
  nav_journal:      "Diario",
  nav_notebook:     "Cuaderno",
  nav_calendar:     "Calendario",
  nav_analytics:    "Análisis",
  nav_reports:      "Informes",
  nav_playbook:     "Estrategias",
  nav_sylledge:     "SYLLEDGE IA",
  nav_backtesting:  "Backtesting",
  nav_brokersync:   "Sincronizar Broker",
  nav_settings:     "Ajustes",
  nav_market_charts:"Gráficos",
  nav_admin:        "Admin",
  nav_upgrade:      "Actualizar a Pro",
  nav_live:         "En vivo",

  save:             "Guardar",
  cancel:           "Cancelar",
  delete:           "Eliminar",
  edit:             "Editar",
  add:              "Añadir",
  clear:            "Limpiar",
  close:            "Cerrar",
  confirm:          "Confirmar",
  search:           "Buscar",
  filter:           "Filtrar",
  export:           "Exportar",
  import:           "Importar",
  loading:          "Cargando…",
  no_data:          "Sin datos",
  view_all:         "Ver todo",
  show_more:        "Mostrar más",
  done:             "Listo",
  retry:            "Reintentar",
  back:             "Atrás",
  next:             "Siguiente",
  yes:              "Sí",
  no:               "No",
  new:              "Nuevo",

  symbol:           "Símbolo",
  direction:        "Dirección",
  entry:            "Entrada",
  exit:             "Salida",
  pnl:              "G/P",
  pips:             "Pips",
  outcome:          "Resultado",
  session:          "Sesión",
  timeframe:        "Temporalidad",
  quality:          "Calidad",
  date:             "Fecha",
  time:             "Hora",
  notes:            "Notas",
  tags:             "Etiquetas",
  actions:          "Acciones",
  win:              "GANANCIA",
  loss:             "PÉRDIDA",
  breakeven:        "NEUTRO",
  buy:              "COMPRA",
  sell:             "VENTA",
  volume:           "Volumen",
  commission:       "Comisión",
  swap:             "Swap",
  total:            "Total",

  dash_title:           "Panel principal",
  dash_new_trade:       "Nueva operación",
  dash_net_pnl:         "G/P neto",
  dash_win_rate:        "Tasa de acierto",
  dash_profit_factor:   "Factor de beneficio",
  dash_expectancy:      "Esperanza matemática",
  dash_sylla_score:     "Puntuación SYLLA",
  dash_equity_curve:    "Curva de capital",
  dash_recent_trades:   "Operaciones recientes",
  dash_activity:        "Actividad reciente",
  dash_today:           "Hoy",
  dash_heatmap:         "Actividad de trading",

  journal_title:        "Diario de trading",
  journal_logged:       "operaciones registradas",
  journal_shown:        "mostradas",
  journal_new_trade:    "Nueva operación",
  journal_table:        "Tabla",
  journal_calendar:     "Calendario",
  journal_filters:      "Filtros",
  journal_clear_all:    "Limpiar todo",
  journal_replay:       "Repetición",
  journal_ai_review:    "Análisis IA",
  journal_min_quality:  "Calidad mínima",
  journal_pnl_range:    "Rango G/P ($)",
  journal_date_range:   "Rango de fechas",
  journal_filter_tag:   "Filtrar por etiqueta",
  journal_running_pnl:  "G/P en curso",
  journal_no_trades:    "Sin operaciones. ¡Pulsa +!",
  journal_pre_entry:    "Contexto (antes de entrada)",
  journal_in_trade:     "En posición",
  journal_closed:       "Cerrado",
  journal_bars:         "velas",

  notebook_title:       "Cuaderno diario",
  notebook_premarket:   "Plan pre-mercado",
  notebook_postmarket:  "Revisión post-mercado",
  notebook_mindset:     "Mentalidad & Disciplina",
  notebook_bias:        "Sesgo de mercado",
  notebook_watchlist:   "Símbolos a vigilar",
  notebook_plan:        "Plan & niveles clave",
  notebook_goals:       "Objetivos de hoy",
  notebook_review:      "¿Cómo fue el día?",
  notebook_lessons:     "Lecciones aprendidas",
  notebook_mistakes:    "Errores a corregir",
  notebook_discipline:  "Disciplina",
  notebook_day_summary: "Resumen del día",
  notebook_no_trades:   "Sin operaciones este día",
  notebook_day_pnl:     "G/P del día",
  notebook_today:       "Hoy",
  notebook_saving:      "Guardando…",
  notebook_saved:       "Guardado",

  analytics_title:      "Análisis",
  reports_title:        "Informes avanzados",
  reports_dimensions:   "50+ dimensiones",
  period_all:           "Todo",
  period_ytd:           "Este año",
  period_1y:            "1 año",
  period_6m:            "6 meses",
  period_3m:            "3 meses",
  period_1m:            "1 mes",
  period_1w:            "1 semana",

  settings_title:       "Ajustes",
  settings_account:     "Cuenta",
  settings_appearance:  "Apariencia",
  settings_language:    "Idioma",
  settings_data:        "Datos & Importación",
  settings_api:         "Claves API",
  settings_notif:       "Notificaciones",
  settings_lang_title:  "Idioma de la app",
  settings_lang_desc:   "Elige el idioma usado en toda la aplicación.",
  settings_lang_saved:  "Idioma guardado",

  broker_title:         "Sincronizar broker",
  broker_connect:       "Conectar & Importar",
  broker_connected:     "¡Conectado!",
  broker_failed:        "Conexión fallida",
  broker_login:         "Número de cuenta MT5",
  broker_server:        "Servidor del broker",
  broker_password:      "Contraseña inversión",
  broker_name:          "Nombre del broker",
  broker_no_accounts:   "Sin cuentas conectadas",

  sylledge_placeholder: "Pregunta a SYLLEDGE sobre tu trading…",
  sylledge_thinking:    "SYLLEDGE está pensando…",

  err_load:             "Error al cargar datos",
  err_save:             "Error al guardar",
  err_not_found:        "No encontrado",
  err_auth:             "Por favor inicia sesión de nuevo",
}

const ar = {
  nav_dashboard:    "لوحة التحكم",
  nav_journal:      "سجل التداول",
  nav_notebook:     "الدفتر",
  nav_calendar:     "التقويم",
  nav_analytics:    "التحليلات",
  nav_reports:      "التقارير",
  nav_playbook:     "الاستراتيجيات",
  nav_sylledge:     "SYLLEDGE AI",
  nav_backtesting:  "الاختبار التاريخي",
  nav_brokersync:   "مزامنة الوسيط",
  nav_settings:     "الإعدادات",
  nav_market_charts:"الرسوم البيانية",
  nav_admin:        "الإدارة",
  nav_upgrade:      "الترقية إلى Pro",
  nav_live:         "مباشر",

  save:             "حفظ",
  cancel:           "إلغاء",
  delete:           "حذف",
  edit:             "تعديل",
  add:              "إضافة",
  clear:            "مسح",
  close:            "إغلاق",
  confirm:          "تأكيد",
  search:           "بحث",
  filter:           "تصفية",
  export:           "تصدير",
  import:           "استيراد",
  loading:          "جاري التحميل…",
  no_data:          "لا توجد بيانات",
  view_all:         "عرض الكل",
  show_more:        "عرض المزيد",
  done:             "تم",
  retry:            "إعادة المحاولة",
  back:             "رجوع",
  next:             "التالي",
  yes:              "نعم",
  no:               "لا",
  new:              "جديد",

  symbol:           "الرمز",
  direction:        "الاتجاه",
  entry:            "الدخول",
  exit:             "الخروج",
  pnl:              "الربح/الخسارة",
  pips:             "نقاط",
  outcome:          "النتيجة",
  session:          "الجلسة",
  timeframe:        "الإطار الزمني",
  quality:          "الجودة",
  date:             "التاريخ",
  time:             "الوقت",
  notes:            "ملاحظات",
  tags:             "الوسوم",
  actions:          "إجراءات",
  win:              "ربح",
  loss:             "خسارة",
  breakeven:        "متعادل",
  buy:              "شراء",
  sell:             "بيع",
  volume:           "الحجم",
  commission:       "العمولة",
  swap:             "السواب",
  total:            "المجموع",

  dash_title:           "لوحة التحكم",
  dash_new_trade:       "صفقة جديدة",
  dash_net_pnl:         "صافي الربح/الخسارة",
  dash_win_rate:        "نسبة الفوز",
  dash_profit_factor:   "معامل الربح",
  dash_expectancy:      "التوقع الرياضي",
  dash_sylla_score:     "نقاط SYLLA",
  dash_equity_curve:    "منحنى رأس المال",
  dash_recent_trades:   "الصفقات الأخيرة",
  dash_activity:        "النشاط الأخير",
  dash_today:           "اليوم",
  dash_heatmap:         "نشاط التداول",

  journal_title:        "سجل التداول",
  journal_logged:       "صفقة مسجلة",
  journal_shown:        "معروضة",
  journal_new_trade:    "صفقة جديدة",
  journal_table:        "جدول",
  journal_calendar:     "تقويم",
  journal_filters:      "الفلاتر",
  journal_clear_all:    "مسح الكل",
  journal_replay:       "إعادة التشغيل",
  journal_ai_review:    "مراجعة الذكاء الاصطناعي",
  journal_min_quality:  "أدنى جودة",
  journal_pnl_range:    "نطاق الربح/الخسارة ($)",
  journal_date_range:   "نطاق التاريخ",
  journal_filter_tag:   "فلترة بالوسم",
  journal_running_pnl:  "الربح/الخسارة الجاري",
  journal_no_trades:    "لا توجد صفقات. اضغط +!",
  journal_pre_entry:    "سياق (قبل الدخول)",
  journal_in_trade:     "في الصفقة",
  journal_closed:       "مغلق",
  journal_bars:         "شمعة",

  notebook_title:       "الدفتر اليومي",
  notebook_premarket:   "خطة ما قبل السوق",
  notebook_postmarket:  "مراجعة ما بعد السوق",
  notebook_mindset:     "الحالة الذهنية & الانضباط",
  notebook_bias:        "توجه السوق",
  notebook_watchlist:   "الرموز المراقبة",
  notebook_plan:        "خطة التداول & المستويات الرئيسية",
  notebook_goals:       "أهداف اليوم",
  notebook_review:      "كيف كان اليوم؟",
  notebook_lessons:     "الدروس المستفادة",
  notebook_mistakes:    "الأخطاء للتصحيح",
  notebook_discipline:  "الانضباط",
  notebook_day_summary: "ملخص اليوم",
  notebook_no_trades:   "لا توجد صفقات هذا اليوم",
  notebook_day_pnl:     "ربح/خسارة اليوم",
  notebook_today:       "اليوم",
  notebook_saving:      "جاري الحفظ…",
  notebook_saved:       "تم الحفظ",

  analytics_title:      "التحليلات",
  reports_title:        "تقارير متقدمة",
  reports_dimensions:   "أكثر من 50 بُعداً",
  period_all:           "الكل",
  period_ytd:           "هذا العام",
  period_1y:            "سنة",
  period_6m:            "6 أشهر",
  period_3m:            "3 أشهر",
  period_1m:            "شهر",
  period_1w:            "أسبوع",

  settings_title:       "الإعدادات",
  settings_account:     "الحساب",
  settings_appearance:  "المظهر",
  settings_language:    "اللغة",
  settings_data:        "البيانات والاستيراد",
  settings_api:         "مفاتيح API",
  settings_notif:       "الإشعارات",
  settings_lang_title:  "لغة التطبيق",
  settings_lang_desc:   "اختر اللغة المستخدمة في جميع أنحاء التطبيق.",
  settings_lang_saved:  "تم حفظ اللغة",

  broker_title:         "مزامنة الوسيط",
  broker_connect:       "اتصال واستيراد الصفقات",
  broker_connected:     "تم الاتصال!",
  broker_failed:        "فشل الاتصال",
  broker_login:         "رقم حساب MT5",
  broker_server:        "خادم الوسيط",
  broker_password:      "كلمة مرور المستثمر",
  broker_name:          "اسم الوسيط",
  broker_no_accounts:   "لا توجد حسابات متصلة",

  sylledge_placeholder: "اسأل SYLLEDGE أي شيء عن تداولك…",
  sylledge_thinking:    "SYLLEDGE يفكر…",

  err_load:             "فشل في تحميل البيانات",
  err_save:             "فشل في الحفظ",
  err_not_found:        "غير موجود",
  err_auth:             "يرجى تسجيل الدخول مجدداً",
}

// ─── Available languages ──────────────────────────────────────────────────────
export const LANGUAGES = [
  { code:"en", label:"English",  flag:"🇬🇧", dir:"ltr" },
  { code:"fr", label:"Français", flag:"🇫🇷", dir:"ltr" },
  { code:"es", label:"Español",  flag:"🇪🇸", dir:"ltr" },
  { code:"ar", label:"العربية",  flag:"🇸🇦", dir:"rtl" },
]

const DICTS = { en, fr, es, ar }

// ─── Context ──────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() =>
    localStorage.getItem("ts_lang") || "en"
  )

  const setLang = (code) => {
    localStorage.setItem("ts_lang", code)
    setLangState(code)
    // Apply RTL/LTR to document
    const info = LANGUAGES.find(l => l.code === code)
    document.documentElement.setAttribute("dir", info?.dir || "ltr")
    document.documentElement.setAttribute("lang", code)
  }

  // Apply on mount
  useEffect(() => {
    const info = LANGUAGES.find(l => l.code === lang)
    document.documentElement.setAttribute("dir", info?.dir || "ltr")
    document.documentElement.setAttribute("lang", lang)
  }, [])

  const t = (key, fallback) => {
    const dict = DICTS[lang] || DICTS.en
    return dict[key] ?? DICTS.en[key] ?? fallback ?? key
  }

  const dir = LANGUAGES.find(l => l.code === lang)?.dir || "ltr"

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider")
  return ctx
}
